### ISSUE TITLE
actor support

### ISSUE THREAD

**Issue by 0x5487** [dapr/go-sdk#21]
Is there any plan to support actor feature in go-sdk?  thank you

**Comment by mchmarny** [comment]
For the client side invocation of the Dapr Actor API, yes. That is certainly on the least and should be added soon. 

For actual go actor support in Dapr that's a larger question given that Dapr doesn't support actors natively. We are reviewing now the effort that it would take to deliver that capability in Dapr. Should have an update soon.

**Comment by nuvetek** [comment]
any updates on actual go support ?

**Comment by mchmarny** [comment]
It's still on the list... the maintainers are focused right now on the Dapr v1.0 (we've shared about the upcoming RC in this week's community call), still, this being entirely in SDK there is a chance we can do something sooner. I know a few people like @yaron2 and @youngbupark have prototyped some ideas there so we we will have to see.

**Comment by tpihl** [comment]
Still nothing?

**Comment by 1046102779** [comment]
subscribe +1

**Comment by LaurenceLiZhixin** [comment]
I'm now working on go-sdk's action api support. In first phase of my work,  the below function points are my aims.

- actor method invocation
- actor timer call invocation 
- actor reminder invocation
- actor deactive

The actor state store may be my second phase of work.
There are the following ideas and ideas in my development process, and I hope to discuss together.

# Actor method call API
## server side API
In the go-sdk method call scene, I designed, the server needs to pass in a defined Actor object(interface{} in golang) that contains many user-defined functions.
```go

func testActorFactory() actor.Actor {
	return &TestActor{
	}
}

type TestActor struct {
}

func (t *TestActor) Type() string {
	return "testActorType"
}

// user defined function 
func (t *TestActor) Invoke(ctx context.Context, req string) (string, error) {
	fmt.Println("get req = ", req)
	return req, nil
}

// user defined function with user defined param
func (t *TestActor) GetUser(ctx context.Context, user *api.User) (*api.User, error) {
	fmt.Println("call get user req = ", user)
	return user, nil
}

```
Developer should register the actor implementation with the SDK to enable support for this ActorType `testActorType`.
```go
func main() {
	s := daprd.NewService(":8080")
	s.RegisterActorImplFactory(testActorFactory) // register factory
	if err := s.Start(); err != nil && err != http.ErrServerClosed { // start actor type
		log.Fatalf("error listenning: %v", err)
	}
}
```

## client side API
The client needs the following client stub as defined by the Actor object method on the server:
```go
type ActorImpl struct {
	GetUser       func(context.Context, *User) (*User, error)
	Invoke        func(context.Context, string) (string, error)
}

func (a *ActorImpl) Type() string {
	return "testActorType" // the type should be compatiable with server side
}

func (a *ActorImpl) ID() string {
	return "ActorImplID123456"
}
```
Call the SDK interface, instance call the stub, you can use the stub to initiate RPC call.
```go
	myActor := new(api.ActorImpl)
	client.ImplActorInteface(myActor)
	usr, err := myActor.GetUser(ctx, &api.User{
		Name: "laurence",
		Age:  22,
	})
	fmt.Println("get user result = ", usr)
```
And get result: `get user result =  &{laurence 22}`

# Problems encountered:
The client stub needs to provide the ActorType and ID, and the server impl needs to provide the ActorType, which I think can be specified by the user by implimenting the following interface:
```go
type ClientImpl interface {
	Type() string
	ID() string
}

type ServerImpl interface {
	Type() string
}
```

But for the server, the Actor on the user side is not easy to get their own Actor ID, the Actor ID is dynamically written, which makes it inconvenient for serveer side to manage the life cycle of their own ID through dapr-client, the Actor SDK provided by daprd is ID granularity.

As for java sdk, Java supports inheriting abstract classes, so this problem can be fixed by asking users to inherit the AbstractActor class, and state store, actorID and other fields related to actor may be managed by AbstractActor. User defined actor only needs to invoke parent class method.

# My proposal
By introducing the actorImplBase class, requiring the user to combine the base class in the Actor class, the Actor ID information can be obtained through the class.
```go
type ServerImplBase struct {
	id string
}

func (b *ServerImplBase) ID() string {
	return b.id
}
func (b *ServerImplBase) SetID(id string)  {
	b.id = id
}
```

```go

type TestActor struct {
	actor.ServerImplBase // combine base struct
	daprClient dapr.Client
}
func (t *TestActor) StopTimer(ctx context.Context, req *api.TimerRequest) error {
	return t.daprClient.UnregisterActorTimer(ctx, &dapr.UnregisterActorTimerRequest{
		ActorType: t.Type(),
		ActorID:   t.ID(), // get id from base to invoke dapr actor api with id granularity
		Name:      req.TimerName,
	})
}
```
For such a design, the next phase of state storage can also be done by a user-defined actor calling methods in the base class.

**Comment by zarba7** [comment]
wait fot actor feature go support!!

**Comment by zarba7** [comment]
wait for actor feature .

**Comment by yaron2** [comment]
@LaurenceLiZhixin thanks for the design proposal, overall I really like it and think it's very Go idiomatic.

Regarding getting the Actor type: can we use Go Reflection to get the type based on the struct name (in your example, `TestActor`) instead of providing a `Type() string` method?

**Comment by artursouza** [comment]
@LaurenceLiZhixin Thanks for this proposal. I like the path you are taking. Regarding @yaron2's idea to use reflection, we provide an annotation in Java because the class name does not necessarily map the type name for the Actor. For example, the class name might have Impl suffix while the actor type does not.

**Comment by LaurenceLiZhixin** [comment]
> @LaurenceLiZhixin thanks for the design proposal, overall I really like it and think it's very Go idiomatic.
> 
> Regarding getting the Actor type: can we use Go Reflection to get the type based on the struct name (in your example, `TestActor`) instead of providing a `Type() string` method?

@yaron2 @artursouza Thank you for your replies, I agree with what artursouza said below. The way that allowing the user to define the Type function loosens the restriction on the Go Type name of actor implement struct imposed by reflection.
And I updated my pr today, pls take a look.

**Comment by tpihl** [comment]
Composition is very ideomatic and probably the correct solution here. I may be a rookie in Go but it's really hard to use composition as a replacement for inherited behavious, specially since the encapsulated struct doesn't "see" the struct it is encapsulated in (unless you do some magic).

So persisting a user defined actor isn't easy to add as a method on actor.ServerImplBase since it need to persist also things from the outer struct. 

Another way could be to modify the required (by registration) factory func to take an ID as argument and by defining the interface as the first part make sure that a user provided type can be utilized with a high degree of freedom.similar to the first part of the solution.

It's hard to find good abstractions and I'm fairly sure that your idea with composition will be great. Most important is to try something.

/T

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/go-sdk/pull/196.
